### ISSUE TITLE
I'll merge this. If any devs think we should change the glob pattern instead we can change the behavior in a secondary PR.

### ISSUE THREAD

**Issue by Yunglow22** [w3c/gpc#76]
I'll merge this. If any devs think we should change the glob pattern instead we can change the behavior in a secondary PR.

_Originally posted by @ReenigneArcher in https://github.com/LizardByte/Sunshine/pull/1972#issuecomment-1874638389_

**Comment by ReenigneArcher** [comment]
What is this? And why are you randomly approving PRs in my repo?
