### ISSUE TITLE
Clarify "targeted advertising" versus "cross-site targeted advertising"?

### ISSUE THREAD

**Issue by michaelkleber** [w3c/gpc#83]
[Section 5.6](https://privacycg.github.io/gpc-spec/#other-jurisdictions-and-privacy-rights) says that GPC is explicitly _not_ intended to prevent "a publisher targeting ads to a user on its website based on that user’s previous activity on that same site".  But Sections 5.2 and 5.3 say that in Colorado and Connecticut, "the GPC signal will be intended to communicate a request to opt out of both the sale of their personal information and the use of their personal information for targeted advertising."

At face value I thought these were in conflict with one another.  Per the side chat in today's meeting, perhaps I am mistaken, and 5.2/5.3 are only trying to refer to "cross-site targeted advertising" rather than all "targeted advertising".

If indeed the phrase "targeted advertising" is meant to always imply "cross-site", we should either explicitly say that, or use the full phrase each time.  (I am personally nervous about explicitly saying that the "cross-site" part is implicit: we are discussion the specific details of many laws, and I wouldn't want us to accidentally mis-characterize some jurisdiction's law based on our adopting a non-universal conventional meaning for the phrase.)

**Comment by npdoty** [comment]
Sounds like there may be agreement here on clarifying the terminology, and also that removing a lot of the legal implications language might decrease the potential conflicts here. Justin to propose a small change as needed.

**Comment by AramZS** [comment]
In the PATWG's charter we talk about 

> Ways in which new features might enable inappropriate processing include (but are not limited to) enabling of [cross-site or cross context recognition ](https://www.w3.org/TR/privacy-principles/#dfn-cross-site-recognition)of users or enabling [same-site or same-context recognition ](https://www.w3.org/TR/privacy-principles/#dfn-same-site-recognition)of users across the clearing of state.

is that maybe the type of language we want to specify here with the same supporting language?

**Comment by j-br0** [comment]
Section 5 of the spec has been dramatically cut down and replaced by expanded legal discussion in Section 4 of the explainer with the merging of PR #81. I believe the new language in both documents is more precise and addresses this issue but if there is still ambiguous language please flag it.

**Comment by michaelkleber** [comment]
Thank you, this seems unambiguous now.
